### ISSUE TITLE
Delete image/tag

### ISSUE THREAD

**Issue by AlbinOS** [heroku/docker-registry-client#16]
Hi everyone,

Thanks a lot for this work, working very well so far.

Do you intend to add a deletion feature to this client ? If not I'm willing to work on it.

**Comment by lorenzobenvenuti** [comment]
@AlbinOS, any progress on this? I've written my implementation, see #21

**Comment by AlbinOS** [comment]
@lorenzobenvenuti, not really, I was waiting for some guidances on how to write it but it's great that you went for it !

**Comment by dmathieu** [comment]
Done in #21.
