### ISSUE TITLE
Suppress or remove logging

### ISSUE THREAD

**Issue by klingtnet** [heroku/docker-registry-client#18]
Why does the library [log certain operations](https://github.com/heroku/docker-registry-client/search?utf8=%E2%9C%93&q=Logf)?
Usually a library does not log anything to stdout/err, instead the output should be returned if necessary.

**Comment by dmathieu** [comment]
You can suppress logging:

```go
r := registry.New(url, username, password)
r.Logf = func(format string, args ...interface{}) {
  // Make this a noop
}
```

**Comment by samifruit514** [comment]
registry.New is calling Ping() from newFromTransport method and Ping() outputs logging with r.Logf("registry.ping url=%s", url). Is there any way we can set the Logf method before the New call?
