### ISSUE TITLE
Provide API to retrieve an image's digest

### ISSUE THREAD

**Issue by omallo** [heroku/docker-registry-client#19]
I've just started using this library and while it works fine for most things, I haven't found a way to retrieve an image's digest. Would it be possible to add this functionality to the library?

Based on the [API docs](https://docs.docker.com/registry/spec/api/), the digest seems to be delivered in the `Docker-Content-Digest` header.

**Comment by omallo** [comment]
I've just seen that this can be accomplished as follows using the `Client` exposed by the library:
```
request, _ := http.NewRequest("HEAD", "https://registry-1.docker.io/v2/library/alpine/manifests/latest", nil)
request.Header.Add("Accept", "application/vnd.docker.distribution.manifest.v2+json")
response, _ := registry.Client.Do(request)
fmt.Println(response.Header["Docker-Content-Digest"][0])
```
However, I think it would still be nice if this functionality would be exposed by the library itself.

**Comment by martinskis** [comment]
Was looking at this a few weeks ago myself. Came back to check and saw your comment. The Docker Manifest in the library would need to be changed to schema2. But I like how you dealt with it, my solution was dirtier :)

**Comment by lorenzobenvenuti** [comment]
I've created a PR with this feature and manifest deletion: #21

**Comment by dmathieu** [comment]
Done in #21.
