### ISSUE TITLE
Docker Distribution dependancy is old.

### ISSUE THREAD

**Issue by jeremyjjbrown** [heroku/docker-registry-client#39]
Docker no longer has a github.com/docker/distribution/digest package and checking out to the version in your GoDeps 99cb7c0946d2f5a380 yeilds 

```controller/docker_test.go:70: cannot use digest (type "github.com/docker/distribution/digest".Digest) as type "github.com/heroku/docker-registry-client/vendor/github.com/docker/distribution/digest".Digest in argument to hub.DownloadLayer```

**Comment by StevenACoffman** [comment]
Fixed in #49
