### ISSUE TITLE
Go build error

### ISSUE THREAD

**Issue by jdcoder** [heroku/docker-registry-client#6]
Using the most recent version of docker registry using the command `go get github.com/docker/distribution/cmd/registry`

Using the Go plugin for IntelliJ, I receive the following error

```
/usr/local/go/bin/go build -o "/private/var/folders/yf/x5rkrcx55qb7ts2kjl7g4l9syc7_5n/T/Build myprogram.go and run3go" -gcflags "-N -l" /Users/thatguy/workspace/myprogram/src/myprogram.go
# github.com/heroku/docker-registry-client/registry
../../work/src/github.com/heroku/docker-registry-client/registry/manifest.go:11: undefined: manifest.SignedManifest
../../work/src/github.com/heroku/docker-registry-client/registry/manifest.go:28: undefined: manifest.SignedManifest
../../work/src/github.com/heroku/docker-registry-client/registry/manifest.go:37: undefined: manifest.SignedManifest
../../work/src/github.com/heroku/docker-registry-client/registry/manifest.go:52: undefined: manifest.ManifestMediaType
```

Here's the source for myprogram.go

```
package main

import (
	"fmt"
	"github.com/heroku/docker-registry-client/registry"
)

func main() {
	fmt.Printf("hello, world\n")

	url      := "https://registry-1.docker.io/"
	username := "" // anonymous
	password := "" // anonymous
	hub, err := registry.New(url, username, password)

	if err != nil {
		panic(err)
	}

	fmt.Printf(hub.URL)

}
```

**Comment by eladg** [comment]
reproduced here.

**Comment by atongen** [comment]
You will need to be sure you're compiling against the same versions of the dependencies included by GoDeps here:

https://github.com/heroku/docker-registry-client/tree/master/Godeps/_workspace

If you are using something like gb, and do `gb vendor fetch github.com/heroku/docker-registry-client`, then you'll likely get build errors.

**Comment by eladg** [comment]
Thanks @atongen, it does indeed that docker/distribution changed (maybe here: distribution/commit/2ff77c00bad8 ?). New to Golang, really confused about how those dependencies works, there is very little good information online...

I'm still figure things out. But this issue is probably not the right place. Thanks!

**Comment by ChristianKniep** [comment]
Hey y'all,

I am a (golang) freshman as well and I am not getting the gist.
I walked through the commands provided, but I still got the same error. 
Could you elaborate on what you did to fix the error? If it would take to long - I'll met some golang folks that could give me a hand next week. But that's next week. :)

**Comment by danielkrainas** [comment]
If you `go get github.com/tools/godep` and use `godep restore` at the root of this project, it will install the needed dependencies at the correct versions. docker-registry-client will then build correctly.

**Comment by danielkrainas** [comment]
this should be able to be closed now.
